### PR TITLE
Rename z/OS Open Tools to zopen community (to be merged on Sept. 20)

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Content Update

## Category

- [x] zopen framework
- [x] Documentation
- [x] CI/CD
- [x] Tools

## Description

As discussed in https://github.com/orgs/ZOSOpenTools/discussions/860, we are changing the name of our community from z/OS Open Tools to the Zopen Community. 

## Related Issues

- Related Issue #
- Closes #

## [optional] Are there any post-deployment tasks or follow-up actions required?
Before the organization rename, we will merge this PR. Then, we will verify:
* Verify CI/CD pipelines are functioning
  * Verify that the builds are functioning
  * Verify that the release json files are being generated properly
* Verify that the zopen install continues to function
* Update all external links to point to zopen-community

### CODE REVIEW

**Comment by v1gnesh** [comment]
Just wondering... does it have to be stylized as `Zopen Community` (capital Z, capital C) instead of `zopen community`?

**Comment by IgorTodorovskiIBM** [comment]
> Just wondering... does it have to be stylized as `Zopen Community` (capital Z, capital C) instead of `zopen community`?

Good question, it doesn't have to be capitalized. Comparing the two, I actually prefer `zopen community`. @MikeFultonDev , your thoughts?

**Comment by AnthonyGiorgio** [comment]
"community" should be in lowercase, but I can go either way on "Zopen" or "zopen".  IBM seems to oscillate on the case of the Z depending on the year.

**Comment by v1gnesh** [comment]
@IgorTodorovskiIBM For info, there is a tool that can be used for bulk changes like this.
https://ast-grep.github.io/
Can't say I know its full power, but it can do a lot for sure.

**Pull request merged**
