### PR TITLE
Change commit user name

### PR DESCRIPTION
**Pull request by v1gnesh**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Content Update

## Category

- [ ] zopen framework
- [ ] Documentation
- [x] CI/CD
- [ ] Tools

## Related Issues

- Related Issue #
- Closes #

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]

**Review by IgorTodorovskiIBM — COMMENTED** [review]
Actually, I believe this correspondings to the github id: https://github.com/zosopentoolsmain . @MikeFultonDev we may need to change this id name as well

**Comment by v1gnesh** [comment]
@IgorTodorovskiIBM when you can spare a few mins, please review.

**Comment by IgorTodorovskiIBM** [comment]
> @IgorTodorovskiIBM when you can spare a few mins, please review.

Do you know if the commit user name needs to match a github id? We still use https://github.com/zosopentoolsmain. We could probably rename it to zopenmain or zopencommunitymain

**Comment by v1gnesh** [comment]
It used to work with the non-existent `bump`. Raising this as just a chore; doesn't really need fixing.
https://github.com/zopencommunity/meta/pull/437

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
